# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-04-14 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlagModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forward_flag', models.BooleanField(default=False)),
                ('forward_left_flag', models.BooleanField(default=False)),
                ('forward_right_flag', models.BooleanField(default=False)),
                ('left_flag', models.BooleanField(default=False)),
                ('right_flag', models.BooleanField(default=False)),
                ('brake_flag', models.BooleanField(default=False)),
                ('reverse_flag', models.BooleanField(default=False)),
                ('reverse_right_flag', models.BooleanField(default=False)),
                ('reverse_left_flag', models.BooleanField(default=False)),
            ],
        ),
    ]
